[package]
name = "unxvdex"
edition = "2024"

[dependencies]
unxvcore = { local = "../unxvcore" }
deepbook = { local = "../deepbookv3/packages/deepbook" }
token = { local = "../deepbookv3/packages/token" }

[addresses]
unxvdex = "0x0"
