export type MarketCategory = 'usdc' | 'usdt' | 'unxv' | 'sui' | 'stablecoins';

export const MARKETS: Record<MarketCategory, string[]> = {
  usdc: [
    'UNXV/USDC','AUSD/USDC','BETH/USDC','CELO/USDC','DEEP/USDC','DRF/USDC','IKA/USDC','NS/USDC','SEND/USDC','SUI/USDC','TYPUS/USDC','USDT/USDC','WAL/USDC','WAVAX/USDC','WBNB/USDC','WBTC/USDC','WETH/USDC','WFTM/USDC','WGLMR/USDC','WMATIC/USDC','WSOL/USDC','WUSDC/USDC','WUSDT/USDC','XBTC/USDC',
  ],
  usdt: [
    'UNXV/USDT','AUSD/USDT','BETH/USDT','CELO/USDT','DEEP/USDT','DRF/USDT','IKA/USDT','NS/USDT','SEND/USDT','SUI/USDT','TYPUS/USDT','USDC/USDT','WAL/USDT','WAVAX/USDT','WBNB/USDT','WBTC/USDT','WETH/USDT','WFTM/USDT','WGLMR/USDT','WMATIC/USDT','WSOL/USDT','WUSDC/USDT','WUSDT/USDT','XBTC/USDT',
  ],
  unxv: [
    'AUSD/UNXV','BETH/UNXV','CELO/UNXV','DEEP/UNXV','DRF/UNXV','IKA/UNXV','NS/UNXV','SEND/UNXV','SUI/UNXV','TYPUS/UNXV','USDC/UNXV','WAL/UNXV','WAVAX/UNXV','WBNB/UNXV','WBTC/UNXV','WETH/UNXV','WFTM/UNXV','WGLMR/UNXV','WMATIC/UNXV','WSOL/UNXV','WUSDC/UNXV','WUSDT/UNXV','XBTC/UNXV',
  ],
  sui: [
    'AUSD/SUI','BETH/SUI','CELO/SUI','DEEP/SUI','DRF/SUI','IKA/SUI','NS/SUI','SEND/SUI','SUI/SUI','TYPUS/SUI','USDC/SUI','WAL/SUI','WAVAX/SUI','WBNB/SUI','WBTC/SUI','WETH/SUI','WFTM/SUI','WGLMR/SUI','WMATIC/SUI','WSOL/SUI','WUSDC/SUI','WUSDT/SUI','XBTC/SUI',
  ],
  stablecoins: [
    'AUSD/USDC','AUSD/USDT','AUSD/WUSDC','AUSD/WUSDT','USDC/USDT','USDC/WUSDC','USDC/WUSDT','USDT/WUSDC','USDT/WUSDT','WUSDC/USDC','WUSDT/USDC','WUSDC/WUSDT',
  ],
};

export function allMarkets(): string[] {
  return Object.values(MARKETS).flat();
}


