[package]
name = "unxversal"
version = "0.9.0"
edition = "2024"
license = "Apache 2.0"
authors = ["Joshua (joshua@unxversal.com)"]

[dependencies]

[dependencies.Switchboard]
local = "../../switchboard/on_demand"

[dependencies.deepbook]
local = "../../deepbookv3packages/deepbook"

[dependencies.Pyth]
local = "../../pyth/contracts"
rev = "sui-contract-testnet"

[addresses]
unxversal = "0x0"
# DeepBook mainnet addresses for integration
deepbook = "0xb29d83c26cdd2a64959263abbcfc4a6937f0c9fccaf98580ca56faded65be244"
# switchboard = "0xe6717fb7c9d44706bf8ce8a651e25c0a7902d32cb0ff40c0976251ce8ac25655"

[dev-addresses]
# switchboard = "0x578b91ec9dcc505439b2f0ec761c23ad2c533a1c23b0467f6c4ae3d9686709f6"