[package]
name = "unxversal"
version = "0.9.0"
edition = "2024"
license = "Apache 2.0"
authors = ["Joshua (joshua@unxversal.com)"]

[dependencies]

[dependencies.deepbook]
local = "../../deepbookv3packages/deepbook"

[dependencies.Pyth]
local = "../../pyth/contracts"

[addresses]
unxversal = "0x0"
# DeepBook mainnet addresses for integration
deepbook = "0xb29d83c26cdd2a64959263abbcfc4a6937f0c9fccaf98580ca56faded65be244"
