[package]
name = "unxversal"
version = "0.9.0"
edition = "2024"
license = "Apache 2.0"
authors = ["Joshua (joshua@unxversal.com)"]

[dependencies]

[dependencies.deepbook]
local = "../../deepbookv3packages/deepbook"

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"

[addresses]
unxversal = "0x0"
# DeepBook mainnet addresses for integration
deepbook = "0xb29d83c26cdd2a64959263abbcfc4a6937f0c9fccaf98580ca56faded65be244"
# pyth = "0x00b53b0f4174108627fbee72e2498b58d6a2714cded53fac537034c220d26302"
# wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"
