[package]
name = "unxversal"
version = "0.9.0"
edition = "2024"
license = "Apache 2.0"
authors = ["Joshua Okolo (unxvjoshua@gmail.com)"]

[dependencies]
[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"
 
[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/mainnet"

[addresses]
unxversal="0x0"
pyth="0x0"

[dev-dependencies]

[dev-dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"
 
[dev-dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/testnet"

[dev-addresses]