import type { LendingComponentProps } from './types';

export const lendingSampleData: LendingComponentProps = {
  address: '0xuser',
  network: 'testnet',
  protocolStatus: { options: true, futures: true, perps: true, lending: true, staking: true, dex: true },
  tvlUsd: 2_400_000_000,
  activeUsers: 12_300,
  markets: [
    {
      id: 'mkt-sui-usdc',
      symbolPair: 'SUI/USDC',
      collateral: { symbol: 'SUI', name: 'Sui', decimals: 9, typeTag: '0x2::sui::SUI' },
      debt: { symbol: 'USDC', name: 'USD Coin', decimals: 6, typeTag: '0xxyz::usdc::USDC' },
      supplyApy: 3.2,
      borrowApy: 5.1,
      totalSupplyDebt: 58_450_000,
      totalBorrowDebt: 31_120_000,
      utilizationRate: 53.2,
      totalLiquidityDebt: 27_330_000,
      maxLtv: 75,
      liquidationThreshold: 80,
      reserveFactor: 15,
      userSuppliedDebt: 12_500,
      userBorrowedDebt: 3_600,
      userCollateral: 420,
    },
    {
      id: 'mkt-deep-usdc',
      symbolPair: 'DEEP/USDC',
      collateral: { symbol: 'DEEP', name: 'DeepBook', decimals: 9, typeTag: '0xdeep::deep::DEEP' },
      debt: { symbol: 'USDC', name: 'USD Coin', decimals: 6, typeTag: '0xxyz::usdc::USDC' },
      supplyApy: 5.6,
      borrowApy: 8.9,
      totalSupplyDebt: 22_000_000,
      totalBorrowDebt: 13_600_000,
      utilizationRate: 61.8,
      totalLiquidityDebt: 8_400_000,
      maxLtv: 70,
      liquidationThreshold: 76,
      reserveFactor: 18,
    },
  ],
  viewMode: 'markets',
  selectedMarketId: undefined,
  isDrawerOpen: false,
  drawerMode: 'supplyDebt',
  inputAmount: 0,
  userBalance: 1000,
  submitting: false,
  onChangeViewMode: () => {},
  onSelectMarket: () => {},
  onOpenDrawer: () => {},
  onCloseDrawer: () => {},
  onChangeDrawerMode: () => {},
  onChangeInputAmount: () => {},
  onSupplyDebt: async () => {},
  onDepositCollateral: async () => {},
  onBorrowDebt: async () => {},
  renderConnect: null,
};


