[package]
name = "unxvlending"
edition = "2024"

[dependencies]
unxvcore = { local = "../unxvcore" }

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"
override = true

[addresses]
unxvlending = "0x0"
